# Generated by Django 5.1.2 on 2024-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripción',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moneda',
            name='valor',
            field=models.PositiveIntegerField(default=1, verbose_name='Valor contra CUP'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_de_adquisición',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coste de adquisición'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_de_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coste de venta'),
        ),
    ]
