# Generated by Django 5.1.2 on 2024-11-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_producto_precio_categoria_descripción_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='moneda',
        ),
        migrations.DeleteModel(
            name='Moneda',
        ),
    ]
