# Generated by Django 5.1.2 on 2024-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_producto_moneda_delete_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_de_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de venta'),
        ),
    ]
