# Generated by Django 5.1.2 on 2024-11-19 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cliente_agenda_clie_user_id_9ff387_idx_and_more'),
        ('stock', '0004_alter_producto_precio_de_venta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['user'], name='stock_categ_user_id_78b9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='stock_categ_nombre_e42369_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['user'], name='stock_produ_user_id_13414f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoría'], name='stock_produ_categor_ff9a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='stock_produ_nombre_fa371d_idx'),
        ),
    ]
