# Generated by Django 5.1.2 on 2024-11-19 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cliente_agenda_clie_user_id_9ff387_idx_and_more'),
        ('stock', '0005_categoria_stock_categ_user_id_78b9ce_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='stock_produ_stock_e173c4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['alerta_stock'], name='stock_produ_alerta__3e81ae_idx'),
        ),
    ]
