# Generated by Django 5.1.2 on 2024-11-20 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cliente_agenda_clie_user_id_9ff387_idx_and_more'),
        ('stock', '0007_alter_categoria_nombre_alter_producto_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='código',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['código'], name='stock_produ_código_e01ca7_idx'),
        ),
    ]
