# Generated by Django 5.1.2 on 2024-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_producto_código_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('UNIDADES', 'Unidades'), ('KILOGRAMOS', 'Kilogramos'), ('LITROS', 'Litros'), ('PALETS', 'Palets'), ('METROS CÚBICOS', 'Metros cúbicos')], default='Unidades', max_length=20, verbose_name='Este producto se vende por'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
