# Generated by Django 5.1.2 on 2024-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_producto_unidad_de_medida_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('UNIDADES', 'Unidades'), ('KILOGRAMOS', 'Kilogramos'), ('LITROS', 'Litros'), ('PALETS', 'Palets'), ('METROS CÚBICOS', 'Metros cúbicos'), ('PROYECTOS', 'Proyectos')], default='Unidades', max_length=20, verbose_name='Este producto se vende por'),
        ),
    ]
