# Generated by Django 5.1.2 on 2025-01-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_proveedor_palabras_clave'),
        ('stock', '0010_alter_producto_unidad_de_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.proveedor'),
        ),
    ]
