# Generated by Django 5.1.2 on 2025-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='código',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_de_adquisición',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coste de adquisición'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_de_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
