version: '2.34'

services:
  django:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4-alpine3.21
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres