# Generated by Django 5.1.2 on 2025-01-22 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cliente_agenda_clie_user_id_9ff387_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='palabras_clave',
            field=models.ManyToManyField(blank=True, to='agenda.palabraclave'),
        ),
        migrations.AddIndex(
            model_name='palabraclave',
            index=models.Index(fields=['user'], name='agenda_pala_user_id_f1670d_idx'),
        ),
        migrations.AddIndex(
            model_name='palabraclave',
            index=models.Index(fields=['palabra'], name='agenda_pala_palabra_523d66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='palabraclave',
            unique_together={('user', 'palabra')},
        ),
    ]
