# Generated by Django 5.1.2 on 2025-01-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_palabraclave_cliente_palabras_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='palabras_clave',
            field=models.ManyToManyField(blank=True, to='agenda.palabraclave'),
        ),
    ]
