# Generated by Django 5.1.2 on 2025-01-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_proveedor_palabras_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='teléfono',
            field=models.CharField(default='+53', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='teléfono',
            field=models.CharField(default='(+53)', max_length=15),
            preserve_default=False,
        ),
    ]
