# Generated by Django 5.1.2 on 2024-10-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='denominación',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.denominación'),
        ),
    ]
