# Generated by Django 5.1.2 on 2024-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_denominación_alter_solicitud_denominación'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='email',
            field=models.EmailField(default='', max_length=15),
        ),
    ]
