# Generated by Django 5.1.2 on 2024-10-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitud_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cantidad_de_referidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
