# Generated by Django 5.1.2 on 2024-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_cantidad_de_referidos_alter_solicitud_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='denominación',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cómo_nos_conoció',
            field=models.CharField(choices=[('AMIGO', 'Un amigo'), ('IG', 'Instagram'), ('DISCORD', 'Discord'), ('LINKEDIN', 'LinkedIn'), ('X', 'X (Twitter)'), ('FB', 'Facebook')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Denominación',
        ),
        migrations.DeleteModel(
            name='Referente',
        ),
    ]
