# Generated by Django 5.1.2 on 2024-11-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_solicitud_denominación_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='denominación',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('ONG', 'ONG'), ('CENTRO', 'Centro Estatal'), ('MIPYME', 'MIPYME'), ('TCP', 'TCP')], default='OTRO', max_length=10),
        ),
    ]
