# Generated by Django 5.1.2 on 2024-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_solicitud_denominación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='denominación',
            field=models.CharField(choices=[('OTRO', 'Otro'), ('ONG', 'ONG'), ('CENTRO', 'Centro Estatal'), ('MIPYME', 'MIPYME'), ('TCP', 'TCP')], max_length=10),
        ),
    ]
