# Generated by Django 5.1.2 on 2024-11-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_solicitud_denominación'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aprobación_de_privacidad',
            field=models.BooleanField(default=False, verbose_name='Acepta nuestra política de privacidad'),
        ),
    ]
