# Generated by Django 5.1.2 on 2024-11-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_solicitud_aprobación_de_privacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='último_pago',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de último pago'),
        ),
    ]
