# Generated by Django 5.1.2 on 2024-12-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_último_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='último_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de último pago'),
        ),
    ]
