# Generated by Django 5.1.2 on 2025-03-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_último_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
