# Generated by Django 5.1.2 on 2025-03-10 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_delete_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cantidad_de_referidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_referido',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cómo_nos_conoció',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='denominación',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='último_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
