# Generated by Django 5.1.2 on 2025-03-10 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_usuario_cantidad_de_referidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='último_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
