# Generated by Django 5.1.2 on 2025-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuario_último_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nro_transacción',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
