# Generated by Django 5.1.2 on 2024-12-05 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cliente_agenda_clie_user_id_9ff387_idx_and_more'),
        ('venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['user'], name='venta_venta_user_id_a696e3_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['código'], name='venta_venta_código_28cd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente'], name='venta_venta_cliente_1b32a5_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='venta_venta_fecha_ca23df_idx'),
        ),
    ]
