# Generated by Django 5.1.2 on 2025-02-07 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_producto_código_and_more'),
        ('venta', '0002_venta_venta_venta_user_id_a696e3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='nombre_producto',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.producto'),
        ),
    ]
