# Generated by Django 5.1.2 on 2025-02-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_detalleventa_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de la venta'),
        ),
    ]
